/**
 * UdonSharp code generation for the state machine (pure functions).
 *
 * Network correctness baked into the output:
 * - triggers check the source state's authority (master / owner / anyone);
 * - ownership is taken before any synced write (owner-only replication);
 * - an anti-reentrance flag prevents triggers fired from OnEnter hooks;
 * - RequestSerialization right after the synced writes (Manual sync);
 * - OnDeserialization applies the state for remotes and late joiners, and
 *   the owner re-serializes in OnPlayerJoined.
 */
import type { SmMachine, SmState, SmTransition, SmVarType } from './types';

export const sanitizeIdent = (raw: string): string => {
  let s = raw.replace(/[^A-Za-z0-9_]/g, '');
  if (s === '' || /^[0-9]/.test(s)) s = '_' + s;
  return s;
};

const pascal = (s: string) => {
  const c = sanitizeIdent(s);
  return c.charAt(0).toUpperCase() + c.slice(1);
};

const upperSnake = (s: string) =>
  sanitizeIdent(s)
    .replace(/([a-z0-9])([A-Z])/g, '$1_$2')
    .toUpperCase();

export const stateConst = (name: string) => `STATE_${upperSnake(name)}`;

const CS_TYPE: Record<SmVarType, string> = {
  bool: 'bool',
  int: 'int',
  float: 'float',
  string: 'string',
};

function literal(type: SmVarType, raw: string): string {
  const v = raw.trim();
  switch (type) {
    case 'bool':
      return /^(true|1)$/i.test(v) ? 'true' : 'false';
    case 'int': {
      const n = parseInt(v, 10);
      return String(Number.isFinite(n) ? n : 0);
    }
    case 'float': {
      const n = parseFloat(v);
      return `${Number.isFinite(n) ? n : 0}f`;
    }
    case 'string':
      return `"${v.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`;
  }
}

const line = (indent: number, text = '') => (text === '' ? '' : '    '.repeat(indent) + text);

function authorityGuard(state: SmState): string[] {
  switch (state.authority) {
    case 'master':
      return [line(3, `if (!Networking.LocalPlayer.isMaster) return; // master authoritative`)];
    case 'owner':
      return [
        line(3, `if (!Networking.IsOwner(Networking.LocalPlayer, gameObject)) return; // owner only`),
      ];
    case 'anyone':
      return [];
  }
}

export function generateStateMachine(m: SmMachine): string {
  const cls = sanitizeIdent(m.className) || 'StateMachine';
  const states = m.states;
  const initial = states.find((s) => s.id === m.initialStateId) ?? states[0];
  const byId = new Map(states.map((s) => [s.id, s]));
  const out: string[] = [];

  out.push(
    `/*`,
    ` * ${cls}.cs — generated by VRC DevKit (UdonSharp state machine)`,
    ` * ${states.length} state(s), ${m.transitions.length} transition(s). Initial: ${initial?.name ?? '?'}.`,
    ` * Fill the OnEnter* hooks with your visuals/audio; regenerate the rest.`,
    ` * https://frankkdarko.github.io/VRCDevKit/#/statemachine`,
    ` */`,
    `using UdonSharp;`,
    `using UnityEngine;`,
    `using VRC.SDKBase;`,
    ``,
    `[UdonBehaviourSyncMode(BehaviourSyncMode.Manual)]`,
    `public class ${cls} : UdonSharpBehaviour`,
    `{`,
    line(1, `// ---- states`),
  );
  states.forEach((s, i) => out.push(line(1, `public const int ${stateConst(s.name)} = ${i};`)));

  out.push(
    ``,
    line(1, `[UdonSynced] private int _state = ${stateConst(initial?.name ?? states[0].name)};`),
  );
  for (const v of m.variables) {
    out.push(
      line(1, `[UdonSynced] private ${CS_TYPE[v.type]} ${sanitizeIdent(v.name)} = ${literal(v.type, v.initial)};`),
    );
  }
  out.push(
    ``,
    line(1, `private int _appliedState = -1; // last state applied locally`),
    line(1, `private bool _transitioning;    // anti-reentrance guard`),
    ``,
    line(1, `public int CurrentState { get { return _state; } }`),
    ``,
    line(1, `private void Start()`),
    line(1, `{`),
    line(2, `ApplyState();`),
    line(1, `}`),
    ``,
    line(1, `// ---- triggers (call directly or via SendCustomEvent)`),
  );

  // Group transitions by trigger name, preserving declaration order.
  const byName = new Map<string, SmTransition[]>();
  for (const t of m.transitions) {
    if (!byId.has(t.from) || !byId.has(t.to)) continue;
    if (!byName.has(t.name)) byName.set(t.name, []);
    byName.get(t.name)!.push(t);
  }

  for (const [name, transitions] of byName) {
    const method = pascal(name);
    out.push(``, line(1, `public void ${method}()`), line(1, `{`));
    out.push(line(2, `if (_transitioning) return; // re-entrance guard`));
    for (const t of transitions) {
      const from = byId.get(t.from)!;
      const to = byId.get(t.to)!;
      out.push(
        line(2, `if (_state == ${stateConst(from.name)})`),
        line(2, `{`),
        ...authorityGuard(from),
      );
      if (t.condition.trim() !== '') {
        out.push(line(3, `if (!(${t.condition.trim()})) return; // condition`));
      }
      out.push(line(3, `DoTransition(${stateConst(to.name)});`), line(3, `return;`), line(2, `}`));
    }
    out.push(line(1, `}`));
  }

  out.push(
    ``,
    line(1, `private void DoTransition(int to)`),
    line(1, `{`),
    line(2, `_transitioning = true;`),
    line(2, `// Only the owner's writes replicate: take ownership before writing.`),
    line(2, `if (!Networking.IsOwner(Networking.LocalPlayer, gameObject))`),
    line(2, `{`),
    line(3, `Networking.SetOwner(Networking.LocalPlayer, gameObject);`),
    line(2, `}`),
    line(2, `_state = to;`),
    line(2, `ApplyEnterAssignments(to);`),
    line(2, `RequestSerialization(); // Manual sync: replicate immediately`),
    line(2, `ApplyState();`),
    line(2, `_transitioning = false;`),
    line(1, `}`),
    ``,
    line(1, `private void ApplyEnterAssignments(int to)`),
    line(1, `{`),
  );
  const withAssignments = states.filter((s) => s.assignments.length > 0);
  if (withAssignments.length === 0) {
    out.push(line(2, `// no synced variable is written on state entry`));
  }
  for (const s of withAssignments) {
    out.push(line(2, `if (to == ${stateConst(s.name)})`), line(2, `{`));
    for (const a of s.assignments) {
      const v = m.variables.find((x) => x.name === a.variable);
      const value = v ? a.value.trim() || literal(v.type, v.initial) : a.value.trim();
      out.push(line(3, `${sanitizeIdent(a.variable)} = ${value};`));
    }
    out.push(line(2, `}`));
  }
  out.push(
    line(1, `}`),
    ``,
    line(1, `// Remotes and late joiners converge here (Manual sync is persistent).`),
    line(1, `public override void OnDeserialization()`),
    line(1, `{`),
    line(2, `ApplyState();`),
    line(1, `}`),
    ``,
    line(1, `// Owner re-serializes so newcomers get the current state right away.`),
    line(1, `public override void OnPlayerJoined(VRCPlayerApi player)`),
    line(1, `{`),
    line(2, `if (Networking.IsOwner(Networking.LocalPlayer, gameObject))`),
    line(2, `{`),
    line(3, `RequestSerialization();`),
    line(2, `}`),
    line(1, `}`),
    ``,
    line(1, `private void ApplyState()`),
    line(1, `{`),
    line(2, `if (_appliedState == _state) return;`),
    line(2, `_appliedState = _state;`),
  );
  for (const s of states) {
    out.push(line(2, `if (_state == ${stateConst(s.name)}) { OnEnter${pascal(s.name)}(); return; }`));
  }
  out.push(line(1, `}`), ``, line(1, `// ---- per-state hooks: put your visuals, audio and colliders here`));
  for (const s of states) {
    out.push(
      ``,
      line(1, `private void OnEnter${pascal(s.name)}()`),
      line(1, `{`),
      line(2, `// TODO: local effects for "${s.name}"`),
      line(1, `}`),
    );
  }
  out.push(`}`, ``);
  return out.join('\n');
}
