/**
 * Output generation for the localization tool (pure functions):
 * - a runtime JSON data file (for the VRCStringDownloader route);
 * - a self-contained UdonSharp behaviour with the strings embedded, which
 *   resolves the player's language and applies texts to referenced
 *   Text / TextMeshProUGUI components.
 */
import type { LocTable } from './types';

/** Runtime-friendly JSON shape (index-aligned arrays). */
export function toRuntimeJson(table: LocTable): string {
  return JSON.stringify(
    {
      version: 1,
      languages: table.languages,
      reference: table.reference,
      keys: table.rows.map((r) => r.key),
      strings: Object.fromEntries(
        table.languages.map((l) => [l, table.rows.map((r) => r.values[l] ?? '')]),
      ),
    },
    null,
    2,
  );
}

const csStr = (s: string) =>
  '"' +
  s.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\r?\n/g, '\\n').replace(/\t/g, '\\t') +
  '"';

const langIdent = (code: string) => {
  const clean = code.replace(/[^A-Za-z0-9]+/g, '_');
  return /^[0-9]/.test(clean) ? '_' + clean : clean;
};

const line = (indent: number, text = '') => (text === '' ? '' : '    '.repeat(indent) + text);

export function generateLocalizationScript(table: LocTable, className = 'WorldLocalization'): string {
  const refIndex = Math.max(0, table.languages.indexOf(table.reference));
  const out: string[] = [];

  out.push(
    `/*`,
    ` * ${className}.cs — generated by VRC DevKit (world localization)`,
    ` * ${table.languages.length} language(s): ${table.languages.join(', ')} — reference: ${table.reference}`,
    ` * ${table.rows.length} key(s). Regenerate this file instead of editing the string arrays.`,
    ` * https://frankkdarko.github.io/VRCDevKit/#/localization`,
    ` */`,
    `using UdonSharp;`,
    `using UnityEngine;`,
    `using UnityEngine.UI;`,
    `using TMPro;`,
    `using VRC.SDKBase;`,
    ``,
    `[UdonBehaviourSyncMode(BehaviourSyncMode.None)]`,
    `public class ${className} : UdonSharpBehaviour`,
    `{`,
    line(1, `[Header("Bindings — same order as the matching key array")]`),
    line(1, `[Tooltip("Unity UI Text components to localize.")]`),
    line(1, `public Text[] uiTexts;`),
    line(1, `[Tooltip("Localization key for each entry of uiTexts.")]`),
    line(1, `public string[] uiTextKeys;`),
    line(1, `[Tooltip("TextMeshProUGUI components to localize.")]`),
    line(1, `public TextMeshProUGUI[] tmpTexts;`),
    line(1, `[Tooltip("Localization key for each entry of tmpTexts.")]`),
    line(1, `public string[] tmpTextKeys;`),
    ``,
    line(1, `private const int REFERENCE_INDEX = ${refIndex};`),
    ``,
    line(1, `private readonly string[] _languages = new string[]`),
    line(1, `{`),
    ...table.languages.map((l) => line(2, `${csStr(l)},`)),
    line(1, `};`),
    ``,
    line(1, `private readonly string[] _keys = new string[]`),
    line(1, `{`),
    ...table.rows.map((r) => line(2, `${csStr(r.key)},`)),
    line(1, `};`),
  );

  for (const lang of table.languages) {
    out.push(
      ``,
      line(1, `private readonly string[] _strings_${langIdent(lang)} = new string[]`),
      line(1, `{`),
      ...table.rows.map((r) => line(2, `${csStr(r.values[lang] ?? '')},`)),
      line(1, `};`),
    );
  }

  out.push(
    ``,
    line(1, `private int _langIndex = REFERENCE_INDEX;`),
    ``,
    line(1, `private void Start()`),
    line(1, `{`),
    line(2, `_langIndex = ResolveLanguage();`),
    line(2, `ApplyAll();`),
    line(1, `}`),
    ``,
    line(1, `/// <summary>Match the player's VRChat language, falling back to the reference.</summary>`),
    line(1, `private int ResolveLanguage()`),
    line(1, `{`),
    line(2, `string current = VRCPlayerApi.GetCurrentLanguage();`),
    line(2, `if (string.IsNullOrEmpty(current)) return REFERENCE_INDEX;`),
    line(2, `for (int i = 0; i < _languages.Length; i++)`),
    line(2, `{`),
    line(3, `if (current == _languages[i] || current.StartsWith(_languages[i])) return i;`),
    line(2, `}`),
    line(2, `return REFERENCE_INDEX;`),
    line(1, `}`),
    ``,
    line(1, `/// <summary>Force a language (e.g. from an in-world selector), then re-apply.</summary>`),
    line(1, `public void SetLanguage(string code)`),
    line(1, `{`),
    line(2, `for (int i = 0; i < _languages.Length; i++)`),
    line(2, `{`),
    line(3, `if (_languages[i] == code)`),
    line(3, `{`),
    line(4, `_langIndex = i;`),
    line(4, `ApplyAll();`),
    line(4, `return;`),
    line(3, `}`),
    line(2, `}`),
    line(2, `Debug.LogWarning("[${className}] Unknown language code: " + code);`),
    line(1, `}`),
    ``,
    line(1, `/// <summary>Current text for a key; falls back to the reference language, then to the key itself.</summary>`),
    line(1, `public string Localize(string key)`),
    line(1, `{`),
    line(2, `for (int i = 0; i < _keys.Length; i++)`),
    line(2, `{`),
    line(3, `if (_keys[i] == key)`),
    line(3, `{`),
    line(4, `string value = GetString(_langIndex, i);`),
    line(4, `if (value == "") value = GetString(REFERENCE_INDEX, i);`),
    line(4, `return value == "" ? key : value;`),
    line(3, `}`),
    line(2, `}`),
    line(2, `return key;`),
    line(1, `}`),
    ``,
    line(1, `private string GetString(int lang, int index)`),
    line(1, `{`),
  );
  table.languages.forEach((lang, i) => {
    out.push(line(2, `if (lang == ${i}) return _strings_${langIdent(lang)}[index];`));
  });
  out.push(
    line(2, `return "";`),
    line(1, `}`),
    ``,
    line(1, `private void ApplyAll()`),
    line(1, `{`),
    line(2, `if (uiTexts != null && uiTextKeys != null)`),
    line(2, `{`),
    line(3, `int count = Mathf.Min(uiTexts.Length, uiTextKeys.Length);`),
    line(3, `for (int i = 0; i < count; i++)`),
    line(3, `{`),
    line(4, `if (uiTexts[i] != null) uiTexts[i].text = Localize(uiTextKeys[i]);`),
    line(3, `}`),
    line(2, `}`),
    line(2, `if (tmpTexts != null && tmpTextKeys != null)`),
    line(2, `{`),
    line(3, `int count = Mathf.Min(tmpTexts.Length, tmpTextKeys.Length);`),
    line(3, `for (int i = 0; i < count; i++)`),
    line(3, `{`),
    line(4, `if (tmpTexts[i] != null) tmpTexts[i].text = Localize(tmpTextKeys[i]);`),
    line(3, `}`),
    line(2, `}`),
    line(1, `}`),
    `}`,
    ``,
  );
  return out.join('\n');
}
